name: "Build Android app and EAS Update"

on:
  push:
    branches:
      - main

jobs:
  build-and-update:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node  
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Setup Keystore
        run: |
          echo ${{ secrets.ANDROID_KEYSTORE_BASE64 }} | base64 --decode > android/app/upload-keystore.jks

      - name: Create credentials.json
        run: |
          echo '{
            "android": {
              "keystore": {
                "keystorePath": "android/app/upload-keystore.jks",
                "keystorePassword": "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}",
                "keyAlias": "${{ secrets.ANDROID_KEY_ALIAS }}",
                "keyPassword": "${{ secrets.ANDROID_KEY_PASSWORD }}"
              }
            }
          }' > credentials.json

      - name: Build APK
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          eas build --platform android --profile production --non-interactive --wait

      - name: Download APK
        run: |
          BUILD_URL=$(eas build:list --json --limit=1 --platform=android --status=finished | jq -r '.[0].artifacts.buildUrl')
          curl -o app-production.apk $BUILD_URL

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app-production.apk
          retention-days: 3

      - name: EAS Update
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas update --auto